#!/bin/bash
# Script to add a user to Linux system
if [ $(id -u) -eq 0 ]; then
	#read -p "Enter username : " username
	#read -s -p "Enter password : " password
	export username=$1
	export password=$2
	egrep "^$username" /etc/passwd >/dev/null
	if [ $? -eq 0 ]; then
		echo "$username exists!"
		exit 1
	else
		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
		useradd -m -p $pass $username
		[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
		echo "$username ALL=(ALL) ALL" >> /etc/sudoers
		
		echo "AllowAgentForwarding yes" >> /etc/ssh/sshd_config
		echo "AllowTcpForwarding yes" >> /etc/ssh/sshd_config
		echo "GatewayPorts yes" >> /etc/ssh/sshd_config
	fi
else
	echo "Only root may add a user to the system"
	exit 2
fi