#!/bin/bash
echo user passed $withUser - password $withPassword
export ENV_USER=${withUser:-sae}
export ENV_PASSWORD=${withPassword:-$ENV_USER}

/usr/bin/containervncserver-setup.sh

/usr/bin/containervncserver-launchvnc.sh $ENV_USER

/bin/bash

